### ISSUE TITLE
Citing

### ISSUE THREAD

**Issue by DomBennett** [ropensci/outsider#2]
Modules should be citable. Add to skeleton to auto create citation.

**Comment by nuest** [comment]
How do you want to achieve this?

If it is about academic citations, it all boils down to having a DOI. I suggest you add a good mechanism to configure and retrieve the DOI of a module, and the in the documentation point module authors to how they can get one (e.g. GitHub>Zenodo, or add the DOI of their reviewd paper).

I think that R does a good job with this, having a function to access the citation of a package but also a free form variant (i.e. just put out the contents of the `CITATION` file).

**Comment by DomBennett** [comment]
The new skeleton allows people to add their name and email to the description. This enables the base cite function in R to produce a simple citation.

(I don't think it's necessary to go all out and start auto-generating DOIs.)
