### ISSUE TITLE
AppVeyor

### ISSUE THREAD

**Issue by DomBennett** [ropensci/outsider#6]
CI for Mac and Windows

**Comment by nuest** [comment]
Let me know if you get stuck here!

**Comment by DomBennett** [comment]
Fixed. https://ci.appveyor.com/project/DomBennett/outsider

But! I can't get linux based containers working.

Docker comes pre-installed when using the "Windows Server 2019" image but only with Windows-based containers. (`docker run hello-world` doesn't work.)

May have to set-up docker with VM as part of the build script. Perhaps using [`chocolatey`](https://chocolatey.org/)?

(Issue part of [ROpenSci review](https://github.com/ropensci/software-review/issues/282))

**Comment by DomBennett** [comment]
Clarification: `docker` is only required for `outsider.base`

AppVeyor project: https://ci.appveyor.com/project/DomBennett/outsider-base
appveyor.yml: https://github.com/AntonelliLab/outsider.base/blob/master/appveyor.yml

**Comment by DomBennett** [comment]
Issue raised here: https://github.com/krlmlr/r-appveyor/issues/168

---

Should be fixed with time.

**Comment by DomBennett** [comment]
Docker running, all passing.
